// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: GC9A01_lvgl_8311

#ifndef _GC9A01_LVGL_8311_UI_H
#define _GC9A01_LVGL_8311_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_temp_label;
extern lv_obj_t * ui_temp_text;
extern lv_obj_t * ui_Label_humidity;
extern lv_obj_t * ui_humidity_text;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1086829539);    // assets/frame_000_delay-0.04s.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
