// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: GC9A01_lvgl_8311

#ifndef _UI_COMP_LABEL2_H
#define _UI_COMP_LABEL2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label2
#define UI_COMP_LABEL2_LABEL2 0
#define _UI_COMP_LABEL2_NUM 1
lv_obj_t * ui_Label2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
