// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: GC9A01_lvgl_8311

#include "ui.h"

void ui_comp_Label2_create_hook(lv_obj_t * comp)
{
}
