// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: GC9A01_lvgl_8311

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, -32);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 20);


    ui_temp_label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_label, -1);
    lv_obj_set_y(ui_temp_label, -65);
    lv_obj_set_align(ui_temp_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_label, "Temp");
    lv_obj_set_style_text_font(ui_temp_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_text, 1);
    lv_obj_set_y(ui_temp_text, -26);
    lv_obj_set_align(ui_temp_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_text, "20");

    ui_Label_humidity = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_humidity, -32);
    lv_obj_set_y(ui_Label_humidity, 76);
    lv_obj_set_align(ui_Label_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_humidity, "Hum:");

    ui_humidity_text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humidity_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity_text, 8);
    lv_obj_set_y(ui_humidity_text, 77);
    lv_obj_set_align(ui_humidity_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity_text, "34");
    lv_obj_set_style_text_decor(ui_humidity_text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

}
